blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: {{REPO_URL}}/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: {{REPO_URL}}#readme
    about: Read the documentation
